classification_dict = {'Apple Apple scab': 0,
            'Apple Black rot': 1,
            'Apple Cedar apple rust': 2,
            'Apple healthy': 3,
            'Blueberry healthy': 4,
            'Cherry Powdery mildew': 5,
            'Cherry healthy': 6,
            'Corn Cercospora leaf spot Gray leaf spot': 7,
            'Corn Common rust': 8,
            'Corn Northern Leaf Blight': 9,
            'Corn healthy': 10,
            'Grape Black rot': 11,
            'Grape Esca (Black Measles)': 12,
            'Grape Leaf blight (Isariopsis Leaf Spot)': 13,
            'Grape healthy': 14,
            'Orange Haunglongbing (Citrus greening)': 15,
            'Peach Bacterial_spot': 16,
            'Peach healthy': 17,
            'Bell_Pepper Bacterial spot': 18,
            'Bell_Pepper healthy': 19,
            'Potato Early blight': 20,
            'Potato Late blight': 21,
            'Potato healthy': 22,
            'Raspberry healthy': 23,
            'Soybean healthy': 24,
            'Squash Powdery mildew': 25,
            'Strawberry Leaf scorch': 26,
            'Strawberry healthy': 27,
            'Tomato Bacterial spot': 28,
            'Tomato Early blight': 29,
            'Tomato Late blight': 30,
            'Tomato Leaf Mold': 31,
            'Tomato Septoria leaf spot': 32,
            'Tomato Spider mites': 33,
            'Tomato Target Spot': 34,
            'Tomato Yellow Leaf Curl Virus': 35,
            'Tomato Tomato Mosaic Virus': 36,
            'Tomato Healthy': 37}

classification_list = list(classification_dict.keys())