# Generated by Django 2.2.7 on 2019-11-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plantImage',
            field=models.ImageField(default='static/default_img.jpg', upload_to='images/'),
        ),
    ]
