# Generated by Django 2.2.7 on 2019-11-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_plantimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plantImage',
            field=models.ImageField(default='images/default_img.jpg', upload_to='images/'),
        ),
    ]
