# Generated by Django 2.2.7 on 2019-11-18 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20191118_2154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plant',
            new_name='Plants',
        ),
    ]
