# Generated by Django 2.2.7 on 2019-11-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_auto_20191118_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='plantImage',
            field=models.ImageField(default='images/default_img.jpg', null=True, upload_to='images/'),
        ),
    ]
