# Generated by Django 2.2.7 on 2019-11-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_auto_20191119_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='plantImage',
            field=models.ImageField(default='images/default_img.jpg', upload_to='images/'),
        ),
    ]
