# Generated by Django 2.2.7 on 2019-11-19 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_auto_20191119_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plants',
            name='name',
        ),
    ]
