# Generated by Django 2.2.7 on 2019-11-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_remove_plants_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='classification',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
