# Generated by Django 2.2.7 on 2019-11-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0011_auto_20191127_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='classification',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
